/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Ctrl_AdministradorUsuarios;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class AdminUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminUsuarios
     */
    public AdminUsuarios() {
        initComponents();

        this.setTitle("Gestionar Usuarios-HourHand");
        this.setSize(new Dimension(638, 453));

        Ctrl_AdministradorUsuarios ContrlAdminUsu = new Ctrl_AdministradorUsuarios();
        ContrlAdminUsu.CargarTablaUsuaios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LbNameUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbContraseña = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BnDarBaja = new javax.swing.JButton();
        BnDarAlta = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CbxPrivilegios = new javax.swing.JComboBox<>();
        BnGuadarCambios = new javax.swing.JButton();
        LbWallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, 230));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrador de Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");

        LbNameUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbNameUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Contraseña");

        LbContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbContraseña.setToolTipText("");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ojito.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BnDarBaja.setBackground(new java.awt.Color(255, 0, 51));
        BnDarBaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnDarBaja.setText("Dar de Baja");
        BnDarBaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnDarBajaActionPerformed(evt);
            }
        });

        BnDarAlta.setBackground(new java.awt.Color(102, 255, 255));
        BnDarAlta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnDarAlta.setText("Dar De Alta");
        BnDarAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnDarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnDarAltaActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Nuevo Usuario");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        CbxPrivilegios.setBackground(new java.awt.Color(255, 255, 51));
        CbxPrivilegios.setEditable(true);
        CbxPrivilegios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CbxPrivilegios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        CbxPrivilegios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BnGuadarCambios.setBackground(new java.awt.Color(255, 51, 255));
        BnGuadarCambios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnGuadarCambios.setText("Guardar");
        BnGuadarCambios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnGuadarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnGuadarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LbNameUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BnDarBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(BnDarAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(BnGuadarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxPrivilegios, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbNameUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BnDarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BnGuadarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbxPrivilegios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 600, 120));

        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo2.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnDarAltaActionPerformed
        if (!LbNameUsuario.getText().isEmpty()) {
            Usuario Usu = new Usuario();
            Ctrl_AdministradorUsuarios controladmin = new Ctrl_AdministradorUsuarios();

            if (controladmin.DarDeAlta(Usu, controladmin.IdUsuario)) {
                JOptionPane.showMessageDialog(null, "Usuario De Alta");
                controladmin.CargarTablaUsuaios();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        }
    }//GEN-LAST:event_BnDarAltaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Ctrl_AdministradorUsuarios ContrlAdminUsu = new Ctrl_AdministradorUsuarios();
            ContrlAdminUsu.VerContraseña();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        RegistroNuevoUsuario RegNewUsu = new RegistroNuevoUsuario();
        RegNewUsu.setVisible(true);
        Ctrl_AdministradorUsuarios ContrlAdminUsu = new Ctrl_AdministradorUsuarios();
        ContrlAdminUsu.CargarTablaUsuaios();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnDarBajaActionPerformed
        if (!LbNameUsuario.getText().isEmpty()) {
            Usuario Usu = new Usuario();
            Ctrl_AdministradorUsuarios controladmin = new Ctrl_AdministradorUsuarios();

            if (controladmin.DarDeBaja(Usu, controladmin.IdUsuario)) {
                JOptionPane.showMessageDialog(null, "Usuario Dado De Baja");
                controladmin.CargarTablaUsuaios();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        }
    }//GEN-LAST:event_BnDarBajaActionPerformed

    private void BnGuadarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnGuadarCambiosActionPerformed
        if (!LbNameUsuario.getText().isEmpty()) {
            Usuario Usu = new Usuario();
            Ctrl_AdministradorUsuarios controladmin = new Ctrl_AdministradorUsuarios();
            
            Usu.setTipoUsuario(CbxPrivilegios.getSelectedItem().toString());
            if (controladmin.PrivilegiosAdmin(Usu, controladmin.IdUsuario)) {
                JOptionPane.showMessageDialog(null, "Actualización Exitosa");
                controladmin.CargarTablaUsuaios();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar datos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        }
    }//GEN-LAST:event_BnGuadarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnDarAlta;
    private javax.swing.JButton BnDarBaja;
    private javax.swing.JButton BnGuadarCambios;
    private javax.swing.JComboBox<String> CbxPrivilegios;
    public static javax.swing.JLabel LbContraseña;
    public static javax.swing.JLabel LbNameUsuario;
    private javax.swing.JLabel LbWallPaper;
    public static javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
