
package Vista;

import Controlador.Ctrl_Compartir;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import static Controlador.Ctrl_tareas.IdTareaSeleccionada;
import Modelo.TareaUsuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class CompartirTarea extends javax.swing.JInternalFrame {

    public CompartirTarea() {
        initComponents();
        this.setSize(new Dimension(485, 212));
        this.setTitle("Compartir Tareas-HourHand");
        LbUsuarioActual.setText(IdUsuarioActual);
        LbTareaSelec.setText(String.valueOf(IdTareaSeleccionada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LbUsuarioActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TfCompartir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LbTareaSelec = new javax.swing.JLabel();
        LbWallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compartir");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tú");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        LbUsuarioActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbUsuarioActual.setForeground(new java.awt.Color(255, 255, 255));
        LbUsuarioActual.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(LbUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id Usuario a Compartir");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        TfCompartir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfCompartir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TfCompartir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 190, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Flecha.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, 40));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Compartir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 131, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tarea");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        LbTareaSelec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbTareaSelec.setForeground(new java.awt.Color(255, 255, 255));
        LbTareaSelec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LbTareaSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo2.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!TfCompartir.getText().isEmpty()) {
            TareaUsuario TarUsu = new TareaUsuario();
            Ctrl_Compartir controlador = new Ctrl_Compartir();

            TarUsu.setUsuario(IdUsuarioActual);
            TarUsu.setTarea(IdTareaSeleccionada);
            TarUsu.setEstado(1);
            TarUsu.setUsuarioACompartir(TfCompartir.getText().trim());

            if (controlador.Guardar(TarUsu)) {
                JOptionPane.showMessageDialog(null, "Compartido");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Compartir la tarea");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Tarea");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LbTareaSelec;
    private javax.swing.JLabel LbUsuarioActual;
    private javax.swing.JLabel LbWallPaper;
    private javax.swing.JTextField TfCompartir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
