package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Maestro;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import Modelo.Maestro;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alvar
 */
public class GestionarMaestros extends javax.swing.JInternalFrame {

    private int IdMaestro;

    public GestionarMaestros() {
        initComponents();
        this.setSize(new Dimension(600, 440));
        this.setTitle("Gestion De Maestros-HourHand");

        this.CargarTablaMateria();
        TfEditDesc.setLineWrap(true);
        TfEditDesc.setWrapStyleWord(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaestros = new javax.swing.JTable();
        PnEditDescripcion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TfEditDesc = new javax.swing.JTextArea();
        PnBotones = new javax.swing.JPanel();
        BnActualizarDesc = new javax.swing.JButton();
        BnEliminarMaestro = new javax.swing.JButton();
        LbWallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnTabla.setBackground(new java.awt.Color(255, 255, 255));

        TablaMaestros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaMaestros);

        javax.swing.GroupLayout PnTablaLayout = new javax.swing.GroupLayout(PnTabla);
        PnTabla.setLayout(PnTablaLayout);
        PnTablaLayout.setHorizontalGroup(
            PnTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnTablaLayout.setVerticalGroup(
            PnTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PnTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 260));

        PnEditDescripcion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Editar Descripción");

        TfEditDesc.setColumns(20);
        TfEditDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfEditDesc.setRows(5);
        jScrollPane2.setViewportView(TfEditDesc);

        javax.swing.GroupLayout PnEditDescripcionLayout = new javax.swing.GroupLayout(PnEditDescripcion);
        PnEditDescripcion.setLayout(PnEditDescripcionLayout);
        PnEditDescripcionLayout.setHorizontalGroup(
            PnEditDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnEditDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnEditDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(PnEditDescripcionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnEditDescripcionLayout.setVerticalGroup(
            PnEditDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnEditDescripcionLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(PnEditDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 430, -1));

        PnBotones.setBackground(new java.awt.Color(255, 255, 255));

        BnActualizarDesc.setBackground(new java.awt.Color(102, 255, 102));
        BnActualizarDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnActualizarDesc.setText("Actualizar");
        BnActualizarDesc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnActualizarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarDescActionPerformed(evt);
            }
        });

        BnEliminarMaestro.setBackground(new java.awt.Color(255, 0, 51));
        BnEliminarMaestro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnEliminarMaestro.setText("Eliminar");
        BnEliminarMaestro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnEliminarMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEliminarMaestroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotonesLayout = new javax.swing.GroupLayout(PnBotones);
        PnBotones.setLayout(PnBotonesLayout);
        PnBotonesLayout.setHorizontalGroup(
            PnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BnActualizarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BnEliminarMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PnBotonesLayout.setVerticalGroup(
            PnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BnActualizarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BnEliminarMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(PnBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 140, -1));

        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnActualizarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarDescActionPerformed
        if (!TfEditDesc.getText().isEmpty()) {
            Maestro maestro = new Maestro();
            Ctrl_Maestro controlmaestro = new Ctrl_Maestro();

            maestro.setDescripcion(TfEditDesc.getText().trim());

            if (controlmaestro.ActualizarMaestro(maestro, IdMaestro)) {
                JOptionPane.showMessageDialog(null, "Maestro Actualizada");
                TfEditDesc.setText("");
                this.CargarTablaMateria();
            } else {
                if (TfEditDesc.getText().length() > 200) {
                    JOptionPane.showMessageDialog(null, "EL TEXTO ES MUY LARGO");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar la Maestro");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Maestro");
        }
    }//GEN-LAST:event_BnActualizarDescActionPerformed

    private void BnEliminarMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEliminarMaestroActionPerformed
        if (!TfEditDesc.getText().isEmpty()) {
            Maestro maestro = new Maestro();
            Ctrl_Maestro controlmaestro = new Ctrl_Maestro();

            maestro.setDescripcion(TfEditDesc.getText().trim());

            if (!controlmaestro.EliminarMaestro(IdMaestro)) {
                JOptionPane.showMessageDialog(null, "Maestro Eliminado");
                TfEditDesc.setText("");
                this.CargarTablaMateria();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar el Maestro");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Maestro");
        }
    }//GEN-LAST:event_BnEliminarMaestroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnActualizarDesc;
    private javax.swing.JButton BnEliminarMaestro;
    private javax.swing.JLabel LbWallPaper;
    private javax.swing.JPanel PnBotones;
    private javax.swing.JPanel PnEditDescripcion;
    private javax.swing.JPanel PnTabla;
    public static javax.swing.JTable TablaMaestros;
    public static javax.swing.JTextArea TfEditDesc;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void CargarTablaMateria() {
        Connection cn = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT IdMaestro,Nombre,Descripcion,Estado FROM tb_maestros WHERE Usuario = '" + IdUsuarioActual + "';";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            GestionarMaestros.TablaMaestros = new JTable(model);
            GestionarMaestros.jScrollPane1.setViewportView(GestionarMaestros.TablaMaestros);

            model.addColumn("IdMaestro");
            model.addColumn("Nombre");
            model.addColumn("Descripcion");
            model.addColumn("Estado");

            while (rs.next()) {
                Object fila[] = new Object[4];
                for (int i = 0; i < 4; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla: " + e);
        }

        TablaMaestros.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int fila_point = TablaMaestros.rowAtPoint(e.getPoint());
                int fila_columna = 0;

                if (fila_point > -1) {
                    IdMaestro = (int) model.getValueAt(fila_point, fila_columna);
                    EnviarDatosMateriaSeleccionada(IdMaestro);
                }
            }
        });

    }

    private void EnviarDatosMateriaSeleccionada(int IdMaestro) {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pat = cn.prepareStatement(
                    "SELECT * FROM tb_maestros WHERE IdMaestro = '" + IdMaestro + "'");
            ResultSet rs = pat.executeQuery();

            if (rs.next()) {
                TfEditDesc.setText(rs.getString("Descripcion"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error cargar maestro: " + e);
        }
    }
}
