package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Materia;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import Modelo.Materia;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author alvar
 */
public class GestionarMaterias extends javax.swing.JInternalFrame {

    

    public GestionarMaterias() {
        initComponents();
        this.setSize(new Dimension(737, 439));
        this.setTitle("Gestionar Materias-HourHand");
        Ctrl_Materia controlmateria = new Ctrl_Materia();
        controlmateria.CargarTablaMateria();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblaMaterias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BnActualizar = new javax.swing.JButton();
        BnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TfDescripcion = new javax.swing.JTextField();
        LbWallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblaMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 710, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BnActualizar.setBackground(new java.awt.Color(51, 204, 0));
        BnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BnActualizar.setText("Actualizar");
        BnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(BnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        BnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        BnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BnEliminar.setText("Eliminar");
        BnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(BnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 130, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Descripción");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TfDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(TfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 530, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 560, 80));

        LbWallPaper.setBackground(new java.awt.Color(255, 255, 255));
        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarActionPerformed
        if (!TfDescripcion.getText().isEmpty()) {
            Materia materia = new Materia();
            Ctrl_Materia controlmateria = new Ctrl_Materia();

            materia.setNombre(TfDescripcion.getText().trim());

            if (controlmateria.Actualizar(materia, controlmateria.IdMateria)) {
                JOptionPane.showMessageDialog(null, "Materia Actualizada");
                TfDescripcion.setText("");
                controlmateria.CargarTablaMateria();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar la Materia");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Materia");
        }
    }//GEN-LAST:event_BnActualizarActionPerformed

    private void BnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEliminarActionPerformed
        if (!TfDescripcion.getText().isEmpty()) {
            Materia materia = new Materia();
            Ctrl_Materia controlmateria = new Ctrl_Materia();

            materia.setNombre(TfDescripcion.getText().trim());

            if (!controlmateria.Eliminar(controlmateria.IdMateria)) {
                JOptionPane.showMessageDialog(null, "Materia Eliminada");
                TfDescripcion.setText("");
                controlmateria.CargarTablaMateria();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar la Materia");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Materia");
        }
    }//GEN-LAST:event_BnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnActualizar;
    private javax.swing.JButton BnEliminar;
    private javax.swing.JLabel LbWallPaper;
    public static javax.swing.JTable TblaMaterias;
    public static javax.swing.JTextField TfDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    

}
