package Vista;

import Controlador.Ctrl_Clases;
import Modelo.Clases;
import static Vista.MenuPrincipal.JDesktopPaneMenu;
import java.awt.Dimension;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class GestionarHorario extends javax.swing.JInternalFrame {

    public GestionarHorario() {
        initComponents();
        this.setTitle("Horario-HourHand");
        this.setSize(new Dimension(711, 437));

        Ctrl_Clases ControlClases = new Ctrl_Clases();
            ControlClases.CargarTablaClases();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHorario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        CbxDiaSemana = new javax.swing.JComboBox<>();
        BnFiltro = new javax.swing.JButton();
        BnAgregar = new javax.swing.JButton();
        BnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TfClase = new javax.swing.JTextField();
        WallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TablaHorario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaHorario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 680, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        CbxDiaSemana.setBackground(new java.awt.Color(153, 255, 255));
        CbxDiaSemana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CbxDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        CbxDiaSemana.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BnFiltro.setBackground(new java.awt.Color(153, 255, 255));
        BnFiltro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BnFiltro.setText("Aplicar Filtro");
        BnFiltro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnFiltroActionPerformed(evt);
            }
        });

        BnAgregar.setBackground(new java.awt.Color(102, 255, 51));
        BnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BnAgregar.setText("Agrerar");
        BnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnAgregarActionPerformed(evt);
            }
        });

        BnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        BnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BnEliminar.setText("Eliminar");
        BnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hora Entrada");

        TfClase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TfClase.setForeground(new java.awt.Color(255, 0, 51));
        TfClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TfClase, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(TfClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 680, 100));

        WallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnFiltroActionPerformed
        
        Ctrl_Clases ControlClases = new Ctrl_Clases();
            ControlClases.CargarTablaClases();
        
        if (CbxDiaSemana.getSelectedItem().toString().equals("Todo")) {
            ControlClases.CargarTablaClases();
        } else {
            ControlClases.CargarTablaClasesConFiltro();
        }
    }//GEN-LAST:event_BnFiltroActionPerformed

    private void BnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnAgregarActionPerformed
        IngresarClases Class = new IngresarClases();
        JDesktopPaneMenu.add(Class);
        Class.setVisible(true);
    }//GEN-LAST:event_BnAgregarActionPerformed

    private void BnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEliminarActionPerformed
        if (!TfClase.getText().isEmpty()) {
            Clases Class = new Clases();
            Ctrl_Clases ControlClass = new Ctrl_Clases();

            Class.setHoraEntrada(TfClase.getText().trim());

            if (!ControlClass.EliminarClase(Class, ControlClass.IdClases)) {
                
                JOptionPane.showMessageDialog(null, "Clase Eliminada");
                ControlClass.CargarTablaClases();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar la clase");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una clase");
        }
    }//GEN-LAST:event_BnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnAgregar;
    private javax.swing.JButton BnEliminar;
    private javax.swing.JButton BnFiltro;
    public static javax.swing.JComboBox<String> CbxDiaSemana;
    public static javax.swing.JTable TablaHorario;
    public static javax.swing.JTextField TfClase;
    private javax.swing.JLabel WallPaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
