package Vista;

import Controlador.Ctrl_TareaUsuario;
import Controlador.Ctrl_tareas;
import Modelo.TareaUsuario;
import Modelo.Tareas;
import static Vista.MenuPrincipal.JDesktopPaneMenu;
import java.awt.Dimension;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class GestionTareas extends javax.swing.JInternalFrame {

    public static int dia, mes, ano;
    public static String Fecha;

    public GestionTareas() {
        initComponents();
        this.setSize(new Dimension(1200, 650));
        this.setTitle("Gestión De Tareas-HourHand");
        Ctrl_tareas controltarea = new Ctrl_tareas();
        controltarea.CargarTablaTareas();
        //Ayuda a que el Text Area Tenga formato y el texto se acomode dentro del mismo
        TaDetalleRequisitos.setLineWrap(true);
        TaDetalleRequisitos.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTareas = new javax.swing.JTable();
        WallPaper = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BnCompartir = new javax.swing.JButton();
        BnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CbxFiltrar = new javax.swing.JComboBox<>();
        BnFiltrar = new javax.swing.JButton();
        BnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaDetalleRequisitos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CbxEstatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        LbHoraEntrega = new javax.swing.JTextField();
        LbFechaEntrega = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LbVisaualizacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TablaTareas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaTareas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 620, 540));

        WallPaper.setBackground(new java.awt.Color(0, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BnCompartir.setBackground(new java.awt.Color(255, 255, 102));
        BnCompartir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnCompartir.setText("Compartir Tarea");
        BnCompartir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnCompartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnCompartirActionPerformed(evt);
            }
        });

        BnActualizar.setBackground(new java.awt.Color(0, 204, 204));
        BnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnActualizar.setText("Actualizar");
        BnActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Filtrar por: ");

        CbxFiltrar.setBackground(new java.awt.Color(255, 153, 153));
        CbxFiltrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CbxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Compartidas", "Pendiente", "En Progreso", "En Espera", "Completada", "Cancelada", "Rechazada", "Atrazada", "En Revisón" }));
        CbxFiltrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BnFiltrar.setBackground(new java.awt.Color(255, 51, 102));
        BnFiltrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BnFiltrar.setText("Aplicar Filtro");
        BnFiltrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnFiltrarActionPerformed(evt);
            }
        });

        BnEliminar.setBackground(new java.awt.Color(51, 51, 255));
        BnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnEliminar.setText("Eliminar");
        BnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(BnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(BnCompartir, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(CbxFiltrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BnCompartir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Requisitos");

        TaDetalleRequisitos.setColumns(20);
        TaDetalleRequisitos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        TaDetalleRequisitos.setRows(5);
        jScrollPane2.setViewportView(TaDetalleRequisitos);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Fecha De Entrega");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Hora De Entrega");

        CbxEstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Progreso", "En Espera", "Completada", "Cancelada", "Rechazada", "Atrazada", "En Revisón" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cambiar Estatus");

        LbHoraEntrega.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        LbFechaEntrega.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Tareas Pendientes");

        LbVisaualizacion.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LbVisaualizacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tarea");

        javax.swing.GroupLayout WallPaperLayout = new javax.swing.GroupLayout(WallPaper);
        WallPaper.setLayout(WallPaperLayout);
        WallPaperLayout.setHorizontalGroup(
            WallPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WallPaperLayout.createSequentialGroup()
                .addGroup(WallPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WallPaperLayout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel2)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WallPaperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGroup(WallPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WallPaperLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WallPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LbFechaEntrega)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(CbxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbHoraEntrega)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(WallPaperLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LbVisaualizacion))
                .addContainerGap())
        );
        WallPaperLayout.setVerticalGroup(
            WallPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WallPaperLayout.createSequentialGroup()
                .addGroup(WallPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WallPaperLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(WallPaperLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbVisaualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        getContentPane().add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1200, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnFiltrarActionPerformed
        Ctrl_tareas controltarea = new Ctrl_tareas();
        if ("Todas".equals(CbxFiltrar.getSelectedItem().toString())) {
            controltarea.CargarTablaTareas();
            BnCompartir.setEnabled(true);
            BnActualizar.setEnabled(true);
        } else if ("Compartidas".equals(CbxFiltrar.getSelectedItem().toString())) {
            BnCompartir.setEnabled(false);
            BnActualizar.setEnabled(false);
            controltarea.CargarTablaTareasCompartida();
        } else {
            controltarea.CargarTablaTareasSinHacer();
            BnCompartir.setEnabled(true);
            BnActualizar.setEnabled(true);
        }

    }//GEN-LAST:event_BnFiltrarActionPerformed

    private void BnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarActionPerformed
        if (!LbVisaualizacion.getText().isEmpty()) {
            Tareas Tar = new Tareas();
            Ctrl_tareas ControlTareas = new Ctrl_tareas();

            Tar.setNombre(LbVisaualizacion.getText().trim());
            Tar.setDescripcion(TaDetalleRequisitos.getText().trim());
            Tar.setEstatus(CbxEstatus.getSelectedItem().toString());

            if (ControlTareas.ActualizarTarea(Tar, ControlTareas.IdTarea)) {

                JOptionPane.showMessageDialog(null, "Tarea Actualizada");
                ControlTareas.CargarTablaTareas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar la tarea");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Tarea");
        }
    }//GEN-LAST:event_BnActualizarActionPerformed

    private void BnCompartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnCompartirActionPerformed
        if (!LbVisaualizacion.getText().isEmpty()) {
            CompartirTarea DeTar = new CompartirTarea();
            GestionTareas gestareas = new GestionTareas();
            JDesktopPaneMenu.add(DeTar);
            DeTar.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Tarea");
        }
    }//GEN-LAST:event_BnCompartirActionPerformed

    private void BnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEliminarActionPerformed

        if ("Compartidas".equals(CbxFiltrar.getSelectedItem().toString())) {
            if (!LbVisaualizacion.getText().isEmpty()) {
                TareaUsuario Tar = new TareaUsuario();
                Ctrl_tareas ControlTareas = new Ctrl_tareas();

                if (!ControlTareas.EliminarTareaCompartida(Tar, ControlTareas.IdTarea)) {
                    JOptionPane.showMessageDialog(null, "Tarea Eliminada");
                    ControlTareas.CargarTablaTareasCompartida();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la tarea");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Tarea");
            }
        } else {
            if (!LbVisaualizacion.getText().isEmpty()) {
                Tareas Tar = new Tareas();
                Ctrl_tareas ControlTareas = new Ctrl_tareas();

                Tar.setNombre(LbVisaualizacion.getText().trim());
                Tar.setDescripcion(TaDetalleRequisitos.getText().trim());

                if (ControlTareas.EliminarTarea(Tar, ControlTareas.IdTarea)) {

                    JOptionPane.showMessageDialog(null, "Tarea Eliminada");
                    ControlTareas.CargarTablaTareas();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la tarea");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Tarea");
            }
        }

    }//GEN-LAST:event_BnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnActualizar;
    private javax.swing.JButton BnCompartir;
    private javax.swing.JButton BnEliminar;
    private javax.swing.JButton BnFiltrar;
    private javax.swing.JComboBox<String> CbxEstatus;
    public static javax.swing.JComboBox<String> CbxFiltrar;
    public static javax.swing.JTextField LbFechaEntrega;
    public static javax.swing.JTextField LbHoraEntrega;
    public static javax.swing.JTextField LbVisaualizacion;
    public static javax.swing.JTextArea TaDetalleRequisitos;
    public static javax.swing.JTable TablaTareas;
    private javax.swing.JPanel WallPaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
