/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorHora;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.TimerTask;
import java.util.Timer;


/**
 *
 * @author alvar
 */
public class HoraYFecha extends javax.swing.JInternalFrame {

    /**
     * Creates new form HoraYFecha
     */
    public HoraYFecha() {
        initComponents();
        this.setTitle("Hora-HourHand");
        this.setSize(new Dimension(223, 101));
        ControladorHora ContHora = new ControladorHora();
        ContHora.Tiempo();

//       ContHora.hora(Reloj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reloj = new javax.swing.JLabel();
        WallPaper = new javax.swing.JLabel();

        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reloj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reloj.setForeground(new java.awt.Color(255, 255, 255));
        Reloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reloj.setText("12:05:29");
        Reloj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 30));

        WallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo2.jpg"))); // NOI18N
        getContentPane().add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Reloj;
    private javax.swing.JLabel WallPaper;
    // End of variables declaration//GEN-END:variables

    
}
