/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Clases;
import static Controlador.Ctrl_Clases.IdMateriaSelec;
import Controlador.Ctrl_Materia;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import Modelo.Clases;
import Modelo.Materia;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class IngresarClases extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clases
     */
    public IngresarClases() {
        initComponents();
        this.setTitle("Clases - HourHand");

        Ctrl_Materia ControlMat = new Ctrl_Materia();
        ControlMat.CargarComboBox2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbxSalida = new javax.swing.JComboBox<>();
        CbxDiaSemana = new javax.swing.JComboBox<>();
        CbxEntrada = new javax.swing.JComboBox<>();
        CbxMateria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        WallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Añadir Clases");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dia De la Semana");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora Entrada");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora Salida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        CbxSalida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CbxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00:00", "06:30:00", "07:00:00", "07:30:00", "08:00:00", "08:30:00", "09:00:00", "09:30:00", "10:00:00", "10:30:00", "11:00:00", "11:30:00", "12:00:00", "01:00:00", "01:30:00", "02:00:00", "02:30:00", "03:00:00", "03:30:00", "04:00:00", "04:30:00", "05:00:00", "05:30:00" }));
        getContentPane().add(CbxSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 130, -1));

        CbxDiaSemana.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CbxDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        getContentPane().add(CbxDiaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 110, 180, -1));

        CbxEntrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CbxEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00:00", "06:30:00", "07:00:00", "07:30:00", "08:00:00", "08:30:00", "09:00:00", "09:30:00", "10:00:00", "10:30:00", "11:00:00", "11:30:00", "12:00:00", "01:00:00", "01:30:00", "02:00:00", "02:30:00", "03:00:00", "03:30:00", "04:00:00", "04:30:00", "05:00:00", "05:30:00" }));
        getContentPane().add(CbxEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 130, -1));

        CbxMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CbxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CbxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 171, 120, 30));

        WallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clases Class = new Clases();
        Materia Mat = new Materia();
        Ctrl_Clases ContrlClases = new Ctrl_Clases();

// Obtener el Id de la materia y establecer el nombre en el objeto Mat
        ContrlClases.MateriaSeleccionada(Mat);

// Establecer el Id de la materia en el objeto Class
        Class.setMateria(IdMateriaSelec);

// Establecer los demás valores en el objeto Class
        Class.setDiaSemana(CbxDiaSemana.getSelectedItem().toString());
        Class.setHoraEntrada(CbxEntrada.getSelectedItem().toString());
        Class.setHoraSalida(CbxSalida.getSelectedItem().toString());
        Class.setEstado(1);

// Guardar el objeto Class y mostrar un mensaje de confirmación o error
        if (ContrlClases.Guardar(Class)) {
            JOptionPane.showMessageDialog(null, "Registro Guardado");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxDiaSemana;
    private javax.swing.JComboBox<String> CbxEntrada;
    public static javax.swing.JComboBox<String> CbxMateria;
    private javax.swing.JComboBox<String> CbxSalida;
    private javax.swing.JLabel WallPaper;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
