/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import static Controlador.Ctrl_Usuario.TipoUsuarioActual;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author alvar
 */
public class MenuPrincipal extends javax.swing.JFrame {
    public static JDesktopPane JDesktopPaneMenu;
    
    public MenuPrincipal() {
        initComponents();
        this.setSize(new Dimension(1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Menú-HourHand");
        
        
        this.setLayout(null);
        JDesktopPaneMenu = new JDesktopPane();
        
        int Ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int Alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.JDesktopPaneMenu.setBounds(0, 0, Ancho, (Alto - 130));
        this.add(JDesktopPaneMenu);
        MnUsuarioAdm.setEnabled(false);
        if (TipoUsuarioActual.equals("Administrador")){
            MnUsuarioAdm.setEnabled(true);
        }
        
        HoraYFecha HraFecha = new HoraYFecha();
        JDesktopPaneMenu.add(HraFecha);
        HraFecha.setVisible(true);
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MnUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnUsuarioAdm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnNuevaMateria = new javax.swing.JMenuItem();
        MnGestionarMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MnTareaPen = new javax.swing.JMenuItem();
        MnNuevaTarea = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MnMaestros = new javax.swing.JMenuItem();
        MnNuevoMaestro = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MnHarario = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        MnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        MnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/usuario.png"))); // NOI18N
        MnUsuario.setText("Usuario");
        MnUsuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        MnUsuario.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/usuario.png"))); // NOI18N
        jMenuItem1.setText("Mi Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnUsuario.add(jMenuItem1);

        MnUsuarioAdm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnUsuarioAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/configuraciones.png"))); // NOI18N
        MnUsuarioAdm.setText("Administar Usuario");
        MnUsuarioAdm.setPreferredSize(new java.awt.Dimension(180, 30));
        MnUsuarioAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUsuarioAdmActionPerformed(evt);
            }
        });
        MnUsuario.add(MnUsuarioAdm);

        jMenuBar1.add(MnUsuario);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IMGMateria.png"))); // NOI18N
        jMenu2.setText("Materias");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        MnNuevaMateria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnNuevaMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/nuevo-producto.png"))); // NOI18N
        MnNuevaMateria.setText("Nueva Materia");
        MnNuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNuevaMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(MnNuevaMateria);

        MnGestionarMateria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnGestionarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Administrar.png"))); // NOI18N
        MnGestionarMateria.setText("Gestionar Materia");
        MnGestionarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnGestionarMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(MnGestionarMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IMGTareas.jpg"))); // NOI18N
        jMenu3.setText("Tareas");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        MnTareaPen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnTareaPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/categorias.png"))); // NOI18N
        MnTareaPen.setText("Tareas Pendientes");
        MnTareaPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTareaPenActionPerformed(evt);
            }
        });
        jMenu3.add(MnTareaPen);

        MnNuevaTarea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnNuevaTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/anadir.png"))); // NOI18N
        MnNuevaTarea.setText("Añadir Tarea");
        MnNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNuevaTareaActionPerformed(evt);
            }
        });
        jMenu3.add(MnNuevaTarea);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cliente.png"))); // NOI18N
        jMenu4.setText("Maestros");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        MnMaestros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnMaestros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/historial1.png"))); // NOI18N
        MnMaestros.setText("Lista de Maestros");
        MnMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMaestrosActionPerformed(evt);
            }
        });
        jMenu4.add(MnMaestros);

        MnNuevoMaestro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnNuevoMaestro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/nuevo-cliente.png"))); // NOI18N
        MnNuevoMaestro.setText("Añadir Maestro");
        MnNuevoMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNuevoMaestroActionPerformed(evt);
            }
        });
        jMenu4.add(MnNuevoMaestro);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IMGHarario.png"))); // NOI18N
        jMenu5.setText("Horario");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        MnHarario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnHarario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reporte1.png"))); // NOI18N
        MnHarario.setText("Ver Mi Horario");
        MnHarario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHararioActionPerformed(evt);
            }
        });
        jMenu5.add(MnHarario);

        jMenuBar1.add(jMenu5);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar-sesion.png"))); // NOI18N
        jMenu7.setText("Cerrar Sesión");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        MnCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar-sesion.png"))); // NOI18N
        MnCerrarSesion.setText("Cerrar Sesión");
        MnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCerrarSesionActionPerformed(evt);
            }
        });
        jMenu7.add(MnCerrarSesion);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnTareaPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTareaPenActionPerformed
        GestionTareas gestareas = new GestionTareas();
        JDesktopPaneMenu.add(gestareas);
        gestareas.setVisible(true);
    }//GEN-LAST:event_MnTareaPenActionPerformed

    private void MnGestionarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnGestionarMateriaActionPerformed
        GestionarMaterias Gesmaterias = new GestionarMaterias();
        JDesktopPaneMenu.add(Gesmaterias);
        Gesmaterias.setVisible(true);
    }//GEN-LAST:event_MnGestionarMateriaActionPerformed

    private void MnNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNuevaMateriaActionPerformed
        NuevaMateria nuevamateria = new NuevaMateria();
        JDesktopPaneMenu.add(nuevamateria);
        nuevamateria.setVisible(true);
    }//GEN-LAST:event_MnNuevaMateriaActionPerformed

    private void MnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCerrarSesionActionPerformed
        this.dispose();
        Login Log = new Login();
        Log.setVisible(true);
    }//GEN-LAST:event_MnCerrarSesionActionPerformed

    private void MnNuevoMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNuevoMaestroActionPerformed
        NuevoMaestro Nmaestro = new NuevoMaestro();
        JDesktopPaneMenu.add(Nmaestro);
        Nmaestro.setVisible(true);
    }//GEN-LAST:event_MnNuevoMaestroActionPerformed

    private void MnMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMaestrosActionPerformed
        GestionarMaestros Gesmaestro = new GestionarMaestros();
        JDesktopPaneMenu.add(Gesmaestro);
        Gesmaestro.setVisible(true);
    }//GEN-LAST:event_MnMaestrosActionPerformed

    private void MnNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNuevaTareaActionPerformed
        TareaNueva tareanueva = new TareaNueva();
        JDesktopPaneMenu.add(tareanueva);
        tareanueva.setVisible(true);
    }//GEN-LAST:event_MnNuevaTareaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MiUsuario MyUsu = new MiUsuario();
        JDesktopPaneMenu.add(MyUsu);
        MyUsu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnUsuarioAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUsuarioAdmActionPerformed
        AdminUsuarios Admusu = new AdminUsuarios();
        JDesktopPaneMenu.add(Admusu);
        Admusu.setVisible(true);
    }//GEN-LAST:event_MnUsuarioAdmActionPerformed

    private void MnHararioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHararioActionPerformed
        GestionarHorario Class = new GestionarHorario();
        JDesktopPaneMenu.add(Class);
        Class.setVisible(true);
    }//GEN-LAST:event_MnHararioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnCerrarSesion;
    private javax.swing.JMenuItem MnGestionarMateria;
    private javax.swing.JMenuItem MnHarario;
    private javax.swing.JMenuItem MnMaestros;
    private javax.swing.JMenuItem MnNuevaMateria;
    private javax.swing.JMenuItem MnNuevaTarea;
    private javax.swing.JMenuItem MnNuevoMaestro;
    private javax.swing.JMenuItem MnTareaPen;
    private javax.swing.JMenu MnUsuario;
    private javax.swing.JMenuItem MnUsuarioAdm;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
