/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Ctrl_Usuario;
import static Controlador.Ctrl_Usuario.ApellidosUsuarioActual;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import static Controlador.Ctrl_Usuario.NickNameUsuarioActual;
import static Controlador.Ctrl_Usuario.NombreUsuarioActual;
import Modelo.Usuario;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class MiUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministracionDeUsuarios
     */
    public MiUsuario() {
        initComponents();
        this.setTitle("Mi Usuario-HourHand");
        
        Ctrl_Usuario contrlUsu = new Ctrl_Usuario();
        contrlUsu.PersonaActual();
        
        LbIdUsuarioActual.setText(IdUsuarioActual);
        LbNombre.setText(NombreUsuarioActual +" "+ApellidosUsuarioActual);
        NickName.setText("@"+NickNameUsuarioActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbIdUsuarioActual = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TpNewPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        TpNewPassConf = new javax.swing.JPasswordField();
        NickName = new javax.swing.JLabel();
        BtGuardarPassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LbWallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbIdUsuarioActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbIdUsuarioActual.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LbIdUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 20));

        LbNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbNombre.setForeground(new java.awt.Color(255, 255, 255));
        LbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 320, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña Nueva");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        TpNewPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TpNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TpNewPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(TpNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        TpNewPassConf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TpNewPassConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TpNewPassConfKeyPressed(evt);
            }
        });
        getContentPane().add(TpNewPassConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, -1));

        NickName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        NickName.setForeground(new java.awt.Color(255, 255, 255));
        NickName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 20));

        BtGuardarPassword.setBackground(new java.awt.Color(102, 204, 255));
        BtGuardarPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtGuardarPassword.setText("Guardar");
        BtGuardarPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtGuardarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(BtGuardarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 130));

        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo2.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtGuardarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarPasswordActionPerformed
        this.ContraseñaNueva();
    }//GEN-LAST:event_BtGuardarPasswordActionPerformed

    private void TpNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpNewPasswordKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            TpNewPassConf.requestFocus();
        }
    }//GEN-LAST:event_TpNewPasswordKeyPressed

    private void TpNewPassConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpNewPassConfKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            this.ContraseñaNueva();
        }
    }//GEN-LAST:event_TpNewPassConfKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGuardarPassword;
    private javax.swing.JLabel LbIdUsuarioActual;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LbWallPaper;
    private javax.swing.JLabel NickName;
    public javax.swing.JPasswordField TpNewPassConf;
    public static javax.swing.JPasswordField TpNewPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
//Boton de guardar en ventana "Mi usuario"
    public void ContraseñaNueva() {
       Ctrl_Usuario controlusu = new Ctrl_Usuario();
        Usuario Usu = new Usuario();
        
        if (TpNewPassword.getText().equals(TpNewPassConf.getText())) {

            Usu.setPassword(TpNewPassword.getText());

            if (controlusu.ActualizarContraseña(Usu)) {
                JOptionPane.showMessageDialog(null, "Contraseña Actualizada");
                TpNewPassword.setText("");
                TpNewPassConf.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar la contraseña");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No coincide!");
        }
       
    }
    
}
