
package Vista;

import Controlador.Ctrl_Maestro;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import static Controlador.Ctrl_Usuario.NombreUsuarioActual;
import Modelo.Maestro;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class NuevoMaestro extends javax.swing.JInternalFrame {

    public NuevoMaestro() {
        initComponents();
        this.setTitle("Nuevo Maestro-HourHand");
        
        TaDescripcion.setLineWrap(true);
        TaDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TfNomMaestro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaDescripcion = new javax.swing.JTextArea();
        BnGuardarMaestro = new javax.swing.JButton();
        LbWallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Maestro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        TfNomMaestro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TfNomMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 450, -1));

        TaDescripcion.setColumns(20);
        TaDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TaDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 450, -1));

        BnGuardarMaestro.setBackground(new java.awt.Color(51, 255, 255));
        BnGuardarMaestro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnGuardarMaestro.setText("Guardar");
        BnGuardarMaestro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnGuardarMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnGuardarMaestroActionPerformed(evt);
            }
        });
        getContentPane().add(BnGuardarMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 80, 30));

        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnGuardarMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnGuardarMaestroActionPerformed
        Maestro Profe = new Maestro();
        Ctrl_Maestro ControlProfes = new Ctrl_Maestro();
            
        if(TfNomMaestro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "INGRESA DATOS COMPLETOS");
        }else{
            if(!ControlProfes.ExisteMaestro(TfNomMaestro.getText().trim())){
                Profe.setNombre(TfNomMaestro.getText().trim());
                Profe.setDescripcion(TaDescripcion.getText().trim());
                Profe.setUsuarioM(IdUsuarioActual);
                Profe.setEstado(1);
                if(ControlProfes.GuardarMaestro(Profe)){
                    JOptionPane.showMessageDialog(null, "DATOS GUARDADOS CORRECTAMENTE");
                    TfNomMaestro.setText("");
                    TaDescripcion.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR, VUELVA A INTENTARLO");
                }
            }else{
                JOptionPane.showMessageDialog(null, "LA MATERIA YA EXISTE!");
            }
        }
    }//GEN-LAST:event_BnGuardarMaestroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnGuardarMaestro;
    private javax.swing.JLabel LbWallPaper;
    private javax.swing.JTextArea TaDescripcion;
    private javax.swing.JTextField TfNomMaestro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
