package Vista;

import Controlador.Ctrl_Materia;
import Controlador.Ctrl_Usuario;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import Modelo.Materia;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class NuevaMateria extends javax.swing.JInternalFrame {

    public static String ComboBox;

    public NuevaMateria() {
        initComponents();
        this.setSize(new Dimension(450, 276));
        this.setTitle("Nueva Materia-HourHand");
        
        TaDescripcion.setLineWrap(true);
        TaDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        LbWallPaper1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CbPrioridad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        LbWallPaper = new javax.swing.JLabel();

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbWallPaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(LbWallPaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel1");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Materia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nueva Materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        TfNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreActionPerformed(evt);
            }
        });
        TfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfNombreKeyPressed(evt);
            }
        });
        getContentPane().add(TfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 90, 30));

        CbPrioridad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));
        getContentPane().add(CbPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Descripcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        TaDescripcion.setColumns(20);
        TaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TaDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 420, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prioridad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        LbWallPaper.setForeground(new java.awt.Color(255, 255, 255));
        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 450, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Materia mate = new Materia();
        Ctrl_Materia controlmateria = new Ctrl_Materia();
//        ComboBox = ComboBox + CbPrioridad.getSelectedItem().toString();

        if (!TfNombre.getText().isEmpty() && TaDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los datos");
        } else {
            if(!controlmateria.ExisteMateria(TfNombre.getText().trim())){
                mate.setNombre(TfNombre.getText().trim());
                mate.setDescripcion(TaDescripcion.getText().trim());
                mate.setPrioridad(CbPrioridad.getSelectedItem().toString());
                mate.setUsuario(IdUsuarioActual);
                mate.setEstado(1);
                if (controlmateria.Guardar(mate)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }
            }else{
                JOptionPane.showMessageDialog(null, "La materia ya existe!");
            }
        }
        
        //Limpiar Campo
        TaDescripcion.setText("");
        TfNombre.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreActionPerformed
        
    }//GEN-LAST:event_TfNombreActionPerformed

    private void TfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNombreKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            TaDescripcion.requestFocus();
        }
    }//GEN-LAST:event_TfNombreKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbPrioridad;
    private javax.swing.JLabel LbWallPaper;
    private javax.swing.JLabel LbWallPaper1;
    private javax.swing.JTextArea TaDescripcion;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
