package Vista;

import Controlador.Ctrl_Persona;
import static Controlador.Ctrl_Persona.IdPersonaActual;
import Controlador.Ctrl_Usuario;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import Modelo.Persona;
import static Modelo.Persona.Perso;
import Modelo.Usuario;
import static Modelo.Usuario.IdUsu;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class RegistroNuevoUsuario extends javax.swing.JFrame {

    public static boolean Repetir = true;

    public RegistroNuevoUsuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(500, 430));
        this.setTitle("Registro-HourHand");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TfNombreReg = new javax.swing.JTextField();
        TfApellidoReg = new javax.swing.JTextField();
        TfUsuarioReg = new javax.swing.JTextField();
        TfContrasenaReg = new javax.swing.JTextField();
        TfNumTelReg = new javax.swing.JTextField();
        BnGuardarReg = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BnCerrarReg = new javax.swing.JButton();
        PsConfContrasenaReg = new javax.swing.JPasswordField();
        LbWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        TfNombreReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfNombreReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfNombreRegKeyPressed(evt);
            }
        });
        getContentPane().add(TfNombreReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, -1));

        TfApellidoReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfApellidoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfApellidoRegKeyPressed(evt);
            }
        });
        getContentPane().add(TfApellidoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 220, -1));

        TfUsuarioReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfUsuarioReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfUsuarioRegKeyPressed(evt);
            }
        });
        getContentPane().add(TfUsuarioReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 450, -1));

        TfContrasenaReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfContrasenaReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfContrasenaRegKeyPressed(evt);
            }
        });
        getContentPane().add(TfContrasenaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, -1));

        TfNumTelReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TfNumTelReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfNumTelRegKeyPressed(evt);
            }
        });
        getContentPane().add(TfNumTelReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, -1));

        BnGuardarReg.setBackground(new java.awt.Color(0, 255, 255));
        BnGuardarReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnGuardarReg.setText("Guardar");
        BnGuardarReg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnGuardarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnGuardarRegActionPerformed(evt);
            }
        });
        getContentPane().add(BnGuardarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmación De Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icon.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 64, 64));

        BnCerrarReg.setBackground(new java.awt.Color(0, 255, 255));
        BnCerrarReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnCerrarReg.setText("Cerrar");
        BnCerrarReg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BnCerrarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnCerrarRegActionPerformed(evt);
            }
        });
        getContentPane().add(BnCerrarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, 30));

        PsConfContrasenaReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PsConfContrasenaReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PsConfContrasenaRegKeyPressed(evt);
            }
        });
        getContentPane().add(PsConfContrasenaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 220, -1));

        LbWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo2.jpg"))); // NOI18N
        getContentPane().add(LbWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnGuardarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnGuardarRegActionPerformed
        this.Registro();
    }//GEN-LAST:event_BnGuardarRegActionPerformed

    private void TfNombreRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNombreRegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            TfApellidoReg.requestFocus();
        }
    }//GEN-LAST:event_TfNombreRegKeyPressed

    private void TfApellidoRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfApellidoRegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            TfUsuarioReg.requestFocus();
        }
    }//GEN-LAST:event_TfApellidoRegKeyPressed

    private void TfUsuarioRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfUsuarioRegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            TfContrasenaReg.requestFocus();
        }
    }//GEN-LAST:event_TfUsuarioRegKeyPressed

    private void TfContrasenaRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfContrasenaRegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            PsConfContrasenaReg.requestFocus();
        }
    }//GEN-LAST:event_TfContrasenaRegKeyPressed

    private void PsConfContrasenaRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PsConfContrasenaRegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            TfNumTelReg.requestFocus();
        }
    }//GEN-LAST:event_PsConfContrasenaRegKeyPressed

    private void TfNumTelRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNumTelRegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.Registro();
        }
    }//GEN-LAST:event_TfNumTelRegKeyPressed

    private void BnCerrarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnCerrarRegActionPerformed
        this.dispose();
    }//GEN-LAST:event_BnCerrarRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroNuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnCerrarReg;
    private javax.swing.JButton BnGuardarReg;
    private javax.swing.JLabel LbWallPaper;
    private javax.swing.JPasswordField PsConfContrasenaReg;
    private javax.swing.JTextField TfApellidoReg;
    private javax.swing.JTextField TfContrasenaReg;
    private javax.swing.JTextField TfNombreReg;
    private javax.swing.JTextField TfNumTelReg;
    private javax.swing.JTextField TfUsuarioReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public void Registro() {

        if (!TfNombreReg.getText().isEmpty() && !TfApellidoReg.getText().isEmpty() && !TfUsuarioReg.getText().isEmpty() && !TfContrasenaReg.getText().isEmpty() && !PsConfContrasenaReg.getText().isEmpty() && !TfNumTelReg.getText().isEmpty()) {
            //Llenar datos de personas

            if (PsConfContrasenaReg.getText().equals(TfContrasenaReg.getText())) {
                Ctrl_Usuario controlUsu = new Ctrl_Usuario();
                Usuario Usu = new Usuario();
                Ctrl_Persona controladorperson = new Ctrl_Persona();
                Persona person = new Persona();
                //Datos de persona
                person.setIdPersona(Perso);
                person.setNombre(TfNombreReg.getText().trim());
                person.setApellidos(TfApellidoReg.getText().trim());
                person.setNumero(TfNumTelReg.getText().trim());

                if (controladorperson.Guardar(person)) {
                    System.out.println("GUARDADO CORRECTAMENTE");
                } else {
                    System.out.println("Error al capturar datos");
                }

                if (!controlUsu.ExisteUsuario(IdUsu.trim())) {
                    Usu.setIdUsuario(IdUsu);
                    Usu.setTipoUsuario("Usuario");
                    Usu.setUsuario(TfUsuarioReg.getText().trim());
                    Usu.setPassword(TfContrasenaReg.getText().trim());
                    Usu.setPersona(Perso);
                    Usu.setEstado(1);
                    if (controlUsu.NuevoUsuario(Usu)) {
                        JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
                        TfNombreReg.setText("");
                        TfApellidoReg.setText("");
                        TfUsuarioReg.setText("");
                        TfContrasenaReg.setText("");
                        PsConfContrasenaReg.setText("");
                        TfNumTelReg.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al capturar datos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El Usuario Existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Su contraseña no coincide");
            }

        } else {
            JOptionPane.showMessageDialog(null, "COMPLETA LOS DATOS");
        }
    }
}
