package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Materia;
import Controlador.Ctrl_MateriaTarea;
import static Controlador.Ctrl_MateriaTarea.IdMateriaSeleccionda;
import Controlador.Ctrl_TareaUsuario;
import static Controlador.Ctrl_Usuario.IdUsuarioActual;
import Controlador.Ctrl_tareas;
import Controlador.Ctrl_tareas.*;
import static Controlador.Ctrl_tareas.IdTareaActual;
import Modelo.Materia;
import Modelo.ModeloTareaUsuarioRel;
import Modelo.TareaMateria;
import Modelo.Tareas;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class TareaNueva extends javax.swing.JInternalFrame {

    public static int dia, mes, ano;
    public static String Fecha;

    public TareaNueva() {
        initComponents();
        this.setSize(new Dimension(601, 438));
        this.setTitle("Añadir Tarea-HourHand");

        Ctrl_Materia ControlMat = new Ctrl_Materia();
        ControlMat.CargarComboBox();

        TaDescripcion.setLineWrap(true);
        TaDescripcion.setWrapStyleWord(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaDescripcion = new javax.swing.JTextArea();
        CbxMateria = new javax.swing.JComboBox<>();
        CbxEstatus = new javax.swing.JComboBox<>();
        DcFechaEntrega = new com.toedter.calendar.JDateChooser();
        CbxHoraEntrega = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Requisitos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        TfNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, -1));

        TaDescripcion.setColumns(20);
        TaDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TaDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, -1));

        CbxMateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CbxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CbxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 110, 140, -1));

        CbxEstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Progreso", "En Espera", "Completada", "Cancelada", "Rechazada", "Atrazada", "En Revisón" }));
        getContentPane().add(CbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 160, 140, -1));
        getContentPane().add(DcFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, -1));

        CbxHoraEntrega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CbxHoraEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00:00", "00:30:00", "01:00:00", "01:30:00", "02:00:00", "02:30:00", "03:00:00", "03:30:00", "04:00:00", "04:30:00", "05:00:00", "05:30:00", "06:00:00", "06:30:00", "07:00:00", "07:30:00", "08:00:00", "08:30:00", "09:00:00", "09:30:00", "10:00:00", "10:30:00", "11:00:00", "11:30:00", "12:00:00", "12:30:00", "13:00:00", "13:30:00", "14:00:00", "14:30:00", "15:00:00", "15:30:00", "16:00:00", "16:30:00", "17:00:00", "17:30:00", "18:00:00", "18:30:00", "19:00:00", "19:30:00", "20:00:00", "20:30:00", "21:00:00", "21:30:00", "22:00:00", "22:30:00", "23:00:00", "23:30:00", "23:59:00" }));
        CbxHoraEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxHoraEntregaActionPerformed(evt);
            }
        });
        getContentPane().add(CbxHoraEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 140, -1));

        Guardar.setBackground(new java.awt.Color(0, 204, 204));
        Guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estatus");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Materia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha De Entrega");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora De Entrega");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nueva Tarea");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbxHoraEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxHoraEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxHoraEntregaActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        mes = DcFechaEntrega.getCalendar().get(Calendar.MONTH) + 1;
        dia = DcFechaEntrega.getCalendar().get(Calendar.DAY_OF_MONTH);
        ano = DcFechaEntrega.getCalendar().get(Calendar.YEAR);

        Fecha = ano + "/" + mes + "/" + dia;
//        ComboBox = ComboBox + CbPrioridad.getSelectedItem().toString();
        TareaMateria Tareamateria = new TareaMateria();
        Materia materia = new Materia();
        Tareas tarea = new Tareas();
        Ctrl_tareas cntareas = new Ctrl_tareas();
        Ctrl_MateriaTarea Matetareas = new Ctrl_MateriaTarea();
        if (!TfNombre.getText().isEmpty() && TaDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los datos");
        } else {
            if (!cntareas.ExisteTarea(TfNombre.getText().trim())) {
                tarea.setNombre(TfNombre.getText().trim());
                tarea.setDescripcion(TaDescripcion.getText().trim());
                tarea.setEstatus(CbxEstatus.getSelectedItem().toString());
                tarea.setHoraEntrega(CbxHoraEntrega.getSelectedItem().toString());
                tarea.setFechaEntrega(Fecha);
                tarea.setEstado(1);
                tarea.setUsuario(IdUsuarioActual);
                if (cntareas.Guardar(tarea)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    TaDescripcion.setText("");
                    TfNombre.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }

                materia.setNombre(CbxMateria.getSelectedItem().toString());
                Matetareas.MateriaSeleccionada(materia);
                cntareas.TareaActual(tarea);
                //Guardamos Datos de la Relacion de la Tarea Con la materia
                //Hacemos la relacion metiendo los datos de la tabla TareaMateria
                Tareamateria.setTarea(IdTareaActual);
                Tareamateria.setMateria(IdMateriaSeleccionda);
                Tareamateria.setEstado(1);
                if (Matetareas.GuardarRelacion(Tareamateria)) {
                    System.out.println("Relacion Guardada");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar la relacion");
                }
            } else {
                JOptionPane.showMessageDialog(null, "La tarea ya existe!");
            }
        }


    }//GEN-LAST:event_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxEstatus;
    private javax.swing.JComboBox<String> CbxHoraEntrega;
    public static javax.swing.JComboBox<String> CbxMateria;
    private com.toedter.calendar.JDateChooser DcFechaEntrega;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextArea TaDescripcion;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
